# Change these first
owner: autovance # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  # Base APIs
  - name: Desk
    url: https://skywalker.autovance.com/health
    headers:
      - "Accept: application/json"
  - name: MyDeal
    url: https://services.autovance.com/public/health
    headers:
      - "Accept: application/json"
  - name: Broker
    url: https://broker.autovance.com/health
    headers:
      - "Accept: application/json"
  - name: Exports
    url: https://services.autovance.com/exports/health
    headers:
      - "Accept: application/json"

  # Experiences
  - name: Authentication
    url: https://skywalker.autovance.com/login
    method: POST
    headers:
      - "Accept: application/json"
      - "api-key: $UPTIME_API_KEY"
      - "content-type: application/json"
    body: '{"autovance-username":"monitor","autovance-password": "monitor"}'
    expectedStatusCodes:
      - 401
      - 422

assignees:
  - autovance/back

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "15 11 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.autovance.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://s3.amazonaws.com/cdn.autovance.com/img/icon.png
  name: Autovance Application Uptime
  introTitle: "Incident and Uptime Monitor for the Autovance Application Suite"
  introMessage: Here you'll find current and historical outages, as well as average response times, for the services powering Autovance Desk, Autovance Menu and MyDeal. Categories affecting specific experiences are listed as well.
  navbar:
    - title: Status
      href: /

commitMessages:
  commitAuthorName: "botovance"
  commitAuthorEmail: "bot@autovance.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
